### ISSUE TITLE
broken midi loops when using fluidsynth

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#962] opened 2023-03-28 07:47 UTC
Testing scenario: Woof! for Win64, win11, cfg generated from scratch, DOOM.WAD, SIGIL_v1_21.WAD
Expected behaviour: in E5M1 the music track should loop at around 1m56s

This is true when using the latest public release (10.5.1) and any midi driver (external, fluidsynth, OPL3)

When using the [latest](https://github.com/fabiangreffrath/woof/actions/runs/4532306731) artifacts, however, the music stops playing at around 1m55s and starts again after a few seconds. This happens only with fluidsynth; external midi devices and opl3 emulation are unaffected.

I've tested older artifacts, trying to identify when this issue originated.
So far, I've found that the issue existed both [before](https://github.com/fabiangreffrath/woof/actions/runs/4459913408) and [after](https://github.com/fabiangreffrath/woof/actions/runs/4469256612) the [most recent](https://github.com/fabiangreffrath/woof/commit/5cbe63c19691064f6030e1b8e478ff74376807dd) fluidsynth-related commit.

**Comment by liPillON** [comment] 2023-03-28 07:58
replacing "libfluidsynth-3.dll" (version 2.3.1) with the one included with the latest official Woof release (version 2.3.0) seems to fix this

**Comment by liPillON** [comment] 2023-03-28 08:25
Tested also the artifacts both [before](https://github.com/fabiangreffrath/woof/actions/runs/4012062647) and [after](https://github.com/fabiangreffrath/woof/actions/runs/4012087775) the most recent commit affecting `src/i_winmusic.c` - no issue there.

**Comment by liPillON** [comment] 2023-03-28 08:45
Yeah, this final test confirms it:  combined with official Fluidsynth Win64 releases:
- [latest Woof Win64 artifacts](https://github.com/fabiangreffrath/woof/actions/runs/4532306731) + [official 2.3.0](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.0) fluidsynt binaries => no issues
- [latest Woof Win64 artifacts](https://github.com/fabiangreffrath/woof/actions/runs/4532306731) + [official 2.3.1](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.1) fluidsynt binaries => broken midi loop

**Comment by rfomin** [comment] 2023-03-28 09:13
> No, we just build with the latest fluidsynth package that's available for vcpkg.

vcpkg supports versioning, in theory we can ship v2.2.8. It seems Crispy is stuck on v2.3.1 for now.

**Comment by fabiangreffrath** [comment] 2023-03-28 09:19
I'd rather have this fixed in Fluidsynth v2.3.2 and use that. 😉

**Comment by liPillON** [comment] 2023-03-28 10:10
> Could you do me a favor and extract the offending MIDI track from the WAD and play it with fluidsynth's own command line player. If the issue is reproducible, please forward it to the fluidsynth bug tracker, becase then there is nothing we can do about it from the Doom source port side of affairs.

The track is 1m55s long and `fluidsynth.exe` plays it until the end, then stops.
AFAIK there is no command line parameter available to tell the application to loop back to the beginning of the track and then start playing it again.
To simulate what I think Woof is telling Fluidsynth to do, I launched `fluidsynth.exe TimGM6mb.sf2 D_E5M1.mid D_E5M1.mid` which I would expect to the track twice, back to back.

With Fluidsynth 2.3.0 the playback is seamless.
With Fluidsynth 2.3.1 there seems to be a few seconds between each track repetition.

If you think this test case is representative of Woof's inner workings, I'll open an issue over at the Fluidsynth project's repository.

**Comment by rfomin** [comment] 2023-03-28 10:17
> If you think this test case is representative of Woof's inner workings, I'll open an issue over at the Fluidsynth project's repository.

I think it's representative. There seems to be a pause at the end of D_E5M1.mid for some reason.

**Comment by fabiangreffrath** [comment] 2023-03-28 10:34
Does the pause appear to be `2000 ms`?

https://github.com/FluidSynth/fluidsynth/commit/752bf65e39731301c2300cf92e3ccc10a22079e8

**Comment by liPillON** [comment] 2023-03-28 10:44
> Does the pause appear to be `2000 ms`?
12 seconds when testing with fluidsynth.exe.
6 seconds when in-game.

**Comment by ceski-1** [comment] 2023-03-28 10:56
Confirmed a roughly 6-7 second pause at the end of the song with FluidSynth. The WinMM backend is seamless. The song itself has no delay at the end of the song either. Built from latest Woof master, using fluidsynth 2.3.1-1.

**Comment by fabiangreffrath** [comment] 2023-03-31 20:45
I have supplied a patch (idea) in the upstream bug report. Nothing more we can do about this here.

**Closed by fabiangreffrath** 2023-03-31 20:45 UTC
Labels: invalid

**Comment by liPillON** [comment] 2023-04-06 10:04
fluidsynth 2.3.2 is out, including a fix for this issue
https://github.com/FluidSynth/fluidsynth/releases/latest

is this where the updated version and checksum should land?
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-fluidsynth

**Comment by fabiangreffrath** [comment] 2023-04-06 10:08
Yes, right.

**Comment by rfomin** [comment] 2023-04-06 10:14
It is not yet in `vcpkg`, we are building a release version with it. https://github.com/microsoft/vcpkg/pull/30625
