### ISSUE TITLE
Legacy of Rust: Crash on Intermission Screen with my config? (Latest Dev Build)

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1880] opened 2024-09-04 03:03 UTC
When testing the new Intermission/Stats screen with Legacy of Rust, the intermission graphics will display just fine, but once it attempts to transition to the next level, the game crashes.

I tried this with a fresh, default config, and somehow the problem went away. 

Here's my config, for context: 
[woof_cfg.zip](https://github.com/user-attachments/files/16860278/woof_cfg.zip)

**Comment by rfomin** [comment] 2024-09-04 04:07
> Here's my config, for context:
> [woof_cfg.zip](https://github.com/user-attachments/files/16860278/woof_cfg.zip)

I can't reproduce this with your config. Did you load old saves to check intermission?

**Comment by OpenRift412** [comment] 2024-09-04 05:42
> > Here's my config, for context:
> > [woof_cfg.zip](https://github.com/user-attachments/files/16860278/woof_cfg.zip)
> 
> I can't reproduce this with your config. Did you load old saves to check intermission?

I did not, no. 

Okay, I just did some testing, turns out it only crashes when the resolution is set to anything above 400% of original (in my case 425% and Maximum since I'm at 1080p).

**Comment by rfomin** [comment] 2024-09-04 08:46
Should be fixed in https://github.com/fabiangreffrath/woof/commit/9b56ae1bd8419e3d2e6ca35d0e14c94ac5406c0e
Thank you.

**Closed** 2024-09-04 09:46 UTC
