### ISSUE TITLE
The new netgame reload level desync demos (even in single player)

### ISSUE THREAD

**Issue by JCDorne** [fabiangreffrath/woof#464] opened 2022-02-24 15:42 UTC
Hello :)
In woof 9.0.0 the netgame reload level desync demos.
In Single player or Netgame. Any complevel
included is a vanilla plutonia demo in skill 5. I should finish the level in 33 seconds. But desync when playback in dsdadoom for example.
[testplutonia.zip](https://github.com/fabiangreffrath/woof/files/8133771/testplutonia.zip)

**Comment by Ch0wW** [comment] 2022-02-24 23:19
Looks like this issue happens for all demos. Vanilla restarts can be fixed by adding `basetic = gametic` in `G_ReloadLevel()`;

MBF however won't fix the issue. Probably is somewhere else?

**Comment by fabiangreffrath** [comment] 2022-02-25 07:19
So, does this have to do with Revenant missles?

**Comment by JCDorne** [comment] 2022-02-25 12:24
In vanilla complevel, the revenant missile is wrong indeed.
Adding `basetic = gametic;` in `G_ReloadLevel` fix this issue.

However, it'll not fix the boom/mbf/mbf21 netgame reload :/

**Comment by fabiangreffrath** [comment] 2022-02-25 12:41
Hm, probably a P_Random() issue?

**Comment by JCDorne** [comment] 2022-02-25 13:22
Something else to note in boom/mbf/mbf21 demos :
In woof 8.1.0, the RNG seed in demo header is reset each time we use the restart level key.
In woof 9.0.0 the RNG seed in demo header is always the same when we use the restart level key.

**Comment by kraflab** [comment] 2022-02-25 20:18
It's important to use a new seed on each restart.

**Comment by fabiangreffrath** [comment] 2022-03-12 12:39
> * Vanilla demos are fine.
> 
> * The first demo recorded is fine in boom, mbf & mbf21.
> 
> * Demos recorded using the restart key desync in boom, mbf & mbf21.
> 
> * When using the restart key in boom, mbf & mbf21 the demo crash with a consistancy failure most of the time.

@JCDorne Could you please do me a favor and upload such a demo sequence here, i.e. where the first one keeps in sync but all subsequent ones desync?

**Comment by fabiangreffrath** [comment] 2022-03-15 08:40
Thank you very much for providing these test cases! It might take some time for me to analyze them, though, or maybe @rfomin even beats me to it. 😄

**Comment by fabiangreffrath** [comment] 2022-03-16 16:13
And as a variation probably this additionally:
```patch
--- a/Source/g_game.c
+++ b/Source/g_game.c
@@ -291,7 +291,7 @@ void G_BuildTiccmd(ticcmd_t* cmd)
   base = I_BaseTiccmd();   // empty, or external driver
   memcpy(cmd, base, sizeof *cmd);
 
-  cmd->consistancy = consistancy[consoleplayer][maketic%BACKUPTICS];
+  cmd->consistancy = consistancy[consoleplayer][(maketic-basetic)%BACKUPTICS];
 
   strafe = M_InputGameActive(input_strafe);
   // [FG] speed key inverts autorun
```

**Comment by fabiangreffrath** [comment] 2022-03-16 16:48
Couldn't reproduce with `-solo-net`, can you confirm?

**Comment by fabiangreffrath** [comment] 2022-03-16 17:14
Also, do both server and clients set the same complevel on the command line?

**Comment by Ch0wW** [comment] 2022-03-16 18:38
> Couldn't reproduce with `-solo-net`, can you confirm?

Can confirm.



> Also, needless to say that both server and clients have to play with the same build, right?
> Also, do both server and clients set the same complevel on the command line?
Yes, and yes. Same settings, same builds for every tests.

**Comment by fabiangreffrath** [comment] 2022-03-16 19:42
It seems that the second Vailant demo desyncs towards the end for the second player. Is it possible that both players end up with different complevels after the reload?

**Comment by JCDorne** [comment] 2022-03-16 20:17
> Could you try this patch, or should I push it as a branch here?

This change create consistency failure in all complevels when reload

> And as a variation probably this additionally:

No more consistency failure, So I tried in -solo-net :
- vanilla first demo playback fine in dsdadoom
- vanilla reload demo playback fine in dsdadoom
- Boom first demo desync in dsdadoom
- Boom reload demo desync in dsdadoom
- MBF first demo desync in dsdadoom
- MBF reload demo desync in dsdadoom

I didn't test -solo-net in 8.0.1 so I don't know the expected behavior here. (if demos are in sync or not)

> Also, needless to say that both server and clients have to play with the same build, right?

Same build and same command line.

> Also, do both server and clients set the same complevel on the command line?

> It seems that the second Vailant demo desyncs towards the end for the second player. Is it possible that both players end up with different complevels after the reload?

Yes. The resulting demos (even with reload) has the correct complevel aswell

**Comment by fabiangreffrath** [comment] 2022-03-16 21:20
> No more consistency failure, So I tried in -solo-net :
 
Hm, doesn't sound like an improvement then, but thanks for testing anyway!

**Comment by fabiangreffrath** [comment] 2022-03-17 14:18
Hm, might as well be a timing issue. All other changes back to normal, does this one help?

```patch
--- a/Source/g_game.c
+++ b/Source/g_game.c
@@ -702,7 +702,7 @@ static void G_ReloadLevel(void)
    if (playeringame[i])
     players[i].playerstate = PST_REBORN;

-  G_DoLoadLevel();
+  gameaction = ga_loadlevel;
 }

 //

```

**Comment by fabiangreffrath** [comment] 2022-03-18 08:40
Lesson learned: `-solo-net` demos are supposed to desync if played back without the `-solo-net` parameter, because `playingame[1] == 0`.

**Comment by fabiangreffrath** [comment] 2022-03-21 08:14
> Hm, might as well be a timing issue. All other changes back to normal, does this one help?
> 
> ```diff
> --- a/Source/g_game.c
> +++ b/Source/g_game.c
> @@ -702,7 +702,7 @@ static void G_ReloadLevel(void)
>     if (playeringame[i])
>      players[i].playerstate = PST_REBORN;
> 
> -  G_DoLoadLevel();
> +  gameaction = ga_loadlevel;
>  }
> 
>  //
> ```

@JCDorne Could you maybe test this approach as well? I am sorry I have to ask you over and over again, but I currently can't find any opportunity to test recording multiplayer demos myself and so far I failed to reproduce the issue with some "fake" multiplayer sessions on a single computer.

**Comment by fabiangreffrath** [comment] 2022-04-10 17:23
https://github.com/fabiangreffrath/woof/commit/eb82b4f64dfe9f0b65ed733acc1535cb959abe6b

**Closed by fabiangreffrath** 2022-04-10 17:23 UTC
Labels: bug, compatibility
