### ISSUE TITLE
improvements to the build system

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#61] opened 2020-02-05 13:32 UTC
@AlexMax Maybe you could have a look at this?

- In the Woof-0.9.0-win32.zip file created by the `make package` rule there are some spurious libraries:

  CheckerDependencyHandlingAnalyzerPlugin.dll
  CheckerOptionHandlingAnalyzerPlugin.dll
  SampleAnalyzerPlugin.dll

  What are they, where are they from and why are they installed into the package?

- The package is currently missing the three SDL2 libraries that the executable depends on. Is it somehow possible to add them (and their respective dependencies) to the package?

- How do I create a source tarball? And how do I add source files (e.g. beta.c, dogs.c, icon.c) that are not listed among WOOF_SOURCES?

**Comment by AlexMax** [comment] 2020-02-05 17:51
>     * In the Woof-0.9.0-win32.zip file created by the `make package` rule there are some spurious libraries:

[Known issue](https://github.com/fabiangreffrath/woof/pull/48#issuecomment-581072888).  It's basically packaging the entire contents of your mingw lib directory by accident.

I do intend on fixing this, but for now you can work around it by using the SDL development libraries downloaded from [the official site](https://www.libsdl.org/download-2.0.php) and pointing `SDL2_*_DIR` at the extracted directory, as that's what I actually tested against.

>     * The package is currently missing the three SDL2 libraries that the executable depends on. Is it somehow possible to add them (and their respective dependencies) to the package?

Same problem, same workaround.

Can you please tell me a little bit about your environment?  What distro are you using, and how are you obtaining SDL2 libraries?

>     * How do I create a source tarball? And how do I add source files (e.g. beta.c, dogs.c, icon.c) that are not listed among WOOF_SOURCES?

There is a `package_source` target that you can make/ninja with.  It will package everything in the source tree except for things that match the `CPACK_SOURCE_IGNORE_FILES` regex.

**Comment by chungy** [comment] 2020-02-05 18:07
> How do I create a source tarball? And how do I add source files (e.g. beta.c, dogs.c, icon.c) that are not listed among WOOF_SOURCES?

I think an advantage of CMake is that you don't have any autogenerated files in the source. `git archive` could be used to generate [reproducible archives](https://reproducible-builds.org/docs/archives/) fairly simply. GitHub uses the same mechanism to generate tar and zip files, so the following example command-line should produce an identical file to what GitHub does:
`git archive -o woof-0.9.0.tar.gz --prefix woof-0.9.0/ woof_0.9.0`

Git only defines tar.gz by default for compressed tar archives, but it's easy to make it know about others. My ~/.gitconfig for example has these lines for both xz and zstd:
```
[tar "tar.xz"]
	command = xz -c
[tar "tar.zst"]
	command = zstd -c
```

**Comment by fabiangreffrath** [comment] 2020-02-06 08:30
> [Known issue](https://github.com/fabiangreffrath/woof/pull/48#issuecomment-581072888). It's basically packaging the entire contents of your mingw lib directory by accident.

No, I don't think it is the same issue. There are only these three spurious libraries in the archive - and I have never seen them before.

> Can you please tell me a little bit about your environment? What distro are you using, and how are you obtaining SDL2 libraries?

This is with MSYS2 on Windows 7 using the mingw32 environment.

This has the `MSYSTEM` environment variable set to `MINGW32` and all binaries and libraries reside in the `/mingw32/bin` directory. Same for mingw64 if you replace all the "32" in my previous sentence with "64". :wink: Maybe we could include a check for this variable in the CMake files and adapt the SDL library search paths accordingly?

> There is a `package_source` target that you can make/ninja with. 

Yep, that's what I was looking for, thanks! ...

> GitHub uses the same mechanism to generate tar and zip files, 

... Whereas indeed @chungy is right. I never have to create source tarballs myself (and never did for Crispy). Once I tag a commit in GIT, GitHub will automatically create a source snapshot for me.

**Comment by AlexMax** [comment] 2020-02-07 02:33
> This is with MSYS2 on Windows 7 using the mingw32 environment.

I tried with the mingw64 environment and got the same "entire build system in my package" problem as @chungy described.  Something might be weird with your environment.

Until I can figure out your issue, I've come up with an action plan to fix @chungy 's issue.  The trouble is that on Windows, I'm grabbing all of the DLL files in the library directory, and although that might work when you download the libraries from libsdl.org, that won't fly on actual mingw installations like the one in MSYS2.  The logic that grabs these DLL files is in the Finder scripts, and these files are then exposed to the outside world through a variable.

My plan is - instead of exposing the individual files, globbed via the Finder script - I plan to expose the library directory itself as a variable.  Then, I will `install` the files by name - something like:

```cmake
install(FILES "${SDL2_LIBRARY_DIR}/SDL2.dll" DESTINATION .)
install(FILES "${SDL2_MIXER_LIBRARY_DIR}/SDL2_mixer.dll" DESTINATION .)
# et cetera...
```

And of course, I'd update the `add_custom_command` post-build steps as well to match.  Not only should this be more precise, but we also get to pick and choose which SDL_mixer media libraries we ship, instead of just shipping them all.

That's my plan.  I've been distracted with other stuff over the past few days, but I will return to this over the weekend.

**Comment by fabiangreffrath** [comment] 2020-02-07 07:45
Turns out the three libraries I found in my ZIP package are part of clang, which is strange as I built the project with gcc. These three libraries are the only three DLL files in my /mingw32/lib directory, maybe this is a hint to you. As I stated earlier, regulat libraries are expected in /mingw32/bin in an MSYS2 environment.

**Comment by fabiangreffrath** [comment] 2020-02-19 15:49
There is one more problem: Under Linux the build system reports it has found `dlopen()`
```
Looking for dlopen in dl - found
```
but the corresponding code in `i_savepng.c` is still not build anyway. 

The macro remains undefined in `config.h`:
```
$ cat build/config.h 
#define PROJECT_NAME "Woof"
#define PROJECT_STRING "Woof 0.9.0"
#define PROJECT_TARNAME "woof"
/* #undef dl_FOUND */
```

**Comment by AlexMax** [comment] 2020-02-19 23:47
I'm looking into the `dl_FOUND` issue.

In the meantime, I've been working on fixes for the original DLL issue.  Which SDL_mixer libraries are you interested in?  Do you want to include all of them, or are there specific ones that you'd prefer to have and others to omit?

**Comment by AlexMax** [comment] 2020-02-20 00:54
Figured out the `dl_FOUND` issue - I fixed it by moving the `configure_file` invocation lower in the file, after the libraries were all found.

**Comment by fabiangreffrath** [comment] 2020-02-20 07:35
> Which SDL_mixer libraries are you interested in? Do you want to include all of them, or are there specific ones that you'd prefer to have and others to omit?

I am not sure I understand the question. Usually it's not a take-or-leave decision. We need all the libraries that SDL2_Mixer.dll is linked against, else it will crash upon loading. For this we somehow need to peak into the symbol table and see which symbols we use of which library. This is what the `cp-with-libs` script did. Not sure if there is anything similar available for CMake.




> Figured out the `dl_FOUND` issue - I fixed it by moving the `configure_file` invocation lower in the file, after the libraries were all found.

Great, thanks! Will you file a PR for this?

**Comment by AlexMax** [comment] 2020-02-21 23:38
I was going to file a PR with both fixes in one, but I see you've already committed a fix.  I plan on finishing up the other fix this weekend, but if I forget, [this](https://github.com/AlexMax/woof/commit/8dd59a730aa7e199fd019e10eb252e244754df04) is the main thrust of the fix.

**Comment by AlexMax** [comment] 2020-02-22 00:42
I have hit upon an unexpected snag.  Upon copying the files from the msys2 installation, I am suddenly getting errors for libraries that are totally out of left field.  I suspect that the libraries in the MSYS library directory are not suitable for redistribution unless you want to balloon the number of DLL files you distribute.  I know that `cp-with-libs` exists, but the approach seems completely wrong-headed to me.

I know everything works peachy keen when you use the official development libraries directly from SDL's website. I suspect those were compiled specifically to be standalone, as opposed to be part of a larger MSYS distribution.

Any thoughts, @fabiangreffrath ?

**Comment by fabiangreffrath** [comment] 2020-02-24 08:32
I know what you are saying, I've been there as well. If you are going to package MSYS2's SDL2_Mixer.dll with all its dependencies, you'll end up with > 20 libraries which include *everything* down to libgcc and friends. Strictly speaking, this is absolutely correct, as the libraries you have linked against just happen to carry this long dependency chain (and `cp-with-libs` would have done exactly the same) but it is a bit impractical from a distribution point of view.

All I want is to distribute a working environment and I am playing the thought of just using the libraries from Crispy doom's release tarball (without libsamplerate and libpng, that is). I also like the idea of using SDL upstream's development libraries, but all this still bears the risk of using different libraries at run-time than were used to link at build-time.

**Comment by AlexMax** [comment] 2020-02-24 23:03
To my mind, using the development libraries from the SDL website seems like the safest play for the most consistent results.  They're official, they're consistent, and more importantly we don't have to build them ourselves.  If anything, there should probably be a warning if the library directory turns out to be `/mingw64/bin`.

Here's how to use the development libraries, assuming you shove the libraries in `mingw-libs`:

```
cmake .. -DCMAKE_BUILD_TYPE=Debug \
    -DSDL2_DIR=../../mingw-libs/SDL2-2.0.10 \
    -DSDL2_MIXER_DIR=../../mingw-libs/SDL2_mixer-2.0.4/ \
    -DSDL2_NET_DIR=../../mingw-libs/SDL2_net-2.0.1
```

And if you're cross-compiling, add this:

```
    -DCMAKE_TOOLCHAIN_FILE=../cmake/CrossToWin64.cmake \
```

**Comment by fabiangreffrath** [comment] 2020-02-25 07:03
Alright, this looks reasonable to me. Is there anything we need to merge from your `cmake-fixes` branch to achieve this?

And do we have to build with `-DCMAKE_BUILD_TYPE=Debug`? Is this necessary?

**Comment by AlexMax** [comment] 2020-02-25 22:30
> Alright, this looks reasonable to me. Is there anything we need to merge from your `cmake-fixes` branch to achieve this?

I need to tidy it up a bit tonight, and I'll open a pull request.

> And do we have to build with `-DCMAKE_BUILD_TYPE=Debug`? Is this necessary?

It's [this](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html).  Without it, it uses the default compiler flags of the given compiler.  With that setting, you get...well, it depends on the compiler, but this is what I found in my CMakeCache.txt file after generating on my Linux box.

```
//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

//Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
```

**Comment by fabiangreffrath** [comment] 2020-02-26 07:30
> Without it, it uses the default compiler flags of the given compiler. With that setting, you get...well, it depends on the compiler, 

Phew, I consider this behaviour pretty engrossing for a build system. I prefer to always build with `-g -O2` and strip out debug symbols later if they prove unnecessary.

**Closed** 2020-03-12 12:51 UTC
Labels: help wanted
