### ISSUE TITLE
Eviternity II Visual Bug

### ISSUE THREAD

**Issue by Enator18** [fabiangreffrath/woof#1413] opened 2024-01-28 04:48 UTC
I experienced this visual bug in Eviternity II MAP18 during my playthrough and then I checked afterward and the bug did not show up using DSDA's software renderer.

Woof:
![image](https://github.com/fabiangreffrath/woof/assets/62544405/06ca7f10-8d63-4ca0-a374-1584b75619b3)

DSDA:
![image](https://github.com/fabiangreffrath/woof/assets/62544405/49ddd3a6-af34-492f-b738-66a486e97b04)

**Comment by fabiangreffrath** [comment] 2024-01-28 07:40
Duplicate of

https://github.com/fabiangreffrath/woof/pull/1352

**Closed by fabiangreffrath** 2024-01-28 07:40 UTC
